# Generated by Django 4.2.30 on 2026-04-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_current_streak_habit_last_marked_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='cached_nudge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='nudge_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
