# Generated by Django 4.2.30 on 2026-04-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_habit_cached_nudge_habit_nudge_generated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('DAILY PRAYERS & BIBLE STUDY', 'Daily Prayers & Bible Study'), ('WORK OUT', 'Work Out'), ('EXAM PREPARATION', 'Exam Preparation'), ('GAMBLING', 'Gambling'), ('WEED SOBER', 'Weed Sober'), ('ALCOHOL SOBER', 'Alcohol Sober'), ('LATE NIGHT EATING', 'Late Night Eating'), ('BUY BUY', 'Buy Buy'), ('CUSTOM', 'Custom Habit')], default='CUSTOM', max_length=225),
        ),
    ]
