# Generated by Django 4.2.30 on 2026-05-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0009_habit_habits_habi_user_id_a3899f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
